# Generated by Django 3.2.7 on 2021-09-02 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='slug')),
                ('desc', models.TextField(verbose_name='description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parent_Category', to='auctions.category', verbose_name='parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=70, null=True, verbose_name='slug')),
                ('desc', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='starting bid')),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True, verbose_name='last bid')),
                ('image', models.ImageField(blank=True, default='bid_imgs/default.png', null=True, upload_to='bid_imgs/', verbose_name='image')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('category', models.ForeignKey(default='misc', on_delete=django.db.models.deletion.RESTRICT, related_name='category', to='auctions.category', verbose_name='category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'ordering': ('-published_date',),
            },
        ),
    ]
