# Generated by Django 3.2.7 on 2021-09-07 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_is_active'),
    ]

    operations = [
        migrations.RenameField('comment', 'bid', 'listing'),
        migrations.RenameField('watchlist', 'bid', 'listing'),
        migrations.RenameModel('Bid', 'Listing'),
        migrations.AlterField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_listing', to='auctions.Listing', verbose_name='listing'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ManyToManyField(related_name='watchlist_listing', to='auctions.Listing', verbose_name='listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='listing_imgs/default.png', null=True, upload_to='listing_imgs/', verbose_name='image'),
        ),
    ]
