# Generated by Django 3.2.7 on 2021-09-07 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_fields1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('-published_date',), 'verbose_name': 'Listing', 'verbose_name_plural': 'Listings'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parent_category', to='auctions.category', verbose_name='parent category'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parent_comment', to='auctions.comment', verbose_name='reply on'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True, verbose_name='last price'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='starting price'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_user', to=settings.AUTH_USER_MODEL, verbose_name='watchlist user'),
        ),
    ]
