# Generated by Django 3.2.7 on 2021-09-09 18:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_add_expiry_alter_category_on_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 18, 17, 0, 930064, tzinfo=utc), verbose_name='expiry date'),
        ),
    ]
