# Generated by Django 3.2.7 on 2021-09-12 05:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_expiry_image_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 5, 21, 52, 884588, tzinfo=utc), verbose_name='expiry date'),
        ),
    ]
